@startuml Tetris


class JuegoTetris
class Control
class Jugador
class Tablero
class Pieza
class Tetromino
class Forma
class Color
class Animacion
class EfectosSonido
class Posicion
class Direccion
class ScoreManager
class TemporizadorJuego
class DetectorColisiones
class EstadoJuego
class EstadoActivo
class EstadoPausado
class EstadoGameOver
class MenuPrincipal
class Boton
class ConfiguracionJuego
class Dificultad
class VelocidadJuego
class PowerUp
class IA
class Aleatorio
class Record
class ContadorPuntos
class MemoriaJuego
class InterfazUsuario


JuegoTetris "1" *-- "1" Control
JuegoTetris "1" *-- "1" Jugador
JuegoTetris "1" *-- "1" Tablero
JuegoTetris "1" o-- "1" ScoreManager
JuegoTetris "1" o-- "1" TemporizadorJuego
JuegoTetris "1" o-- "1" DetectorColisiones
JuegoTetris "1" o-- "1" Animacion
JuegoTetris "1" o-- "1" EfectosSonido
JuegoTetris "1" *-- "1" EstadoJuego
JuegoTetris "1" *-- "1" MenuPrincipal
JuegoTetris "1" *-- "1" ConfiguracionJuego
JuegoTetris "1" *-- "*" PowerUp
JuegoTetris "1" o-- "1" IA

' Nuevas relaciones
JuegoTetris "1" o-- "1" MemoriaJuego
JuegoTetris "1" o-- "1" InterfazUsuario

MemoriaJuego "1" o-- "1" ScoreManager
MemoriaJuego "1" o-- "1" ConfiguracionJuego

InterfazUsuario *-- MenuPrincipal
InterfazUsuario *-- Tablero
InterfazUsuario *-- Animacion

Jugador "1" o-- "1" Control
Jugador "1" o-- "1" Pieza

Pieza "1" *-- "1" Tetromino
Pieza "1" *-- "1" Posicion
Pieza "1" *-- "1" Direccion
Pieza "1" o-- "1" Color
Pieza "1" o-- "0..1" PowerUp

Tablero "1" *-- "0..*" Posicion

Forma "1" *-- "1..*" Tetromino

EstadoActivo --|> EstadoJuego
EstadoPausado --|> EstadoJuego
EstadoGameOver --|> EstadoJuego

MenuPrincipal "1" *-- "1..*" Boton

ConfiguracionJuego "1" *-- "1" Dificultad
ConfiguracionJuego "1" *-- "1" VelocidadJuego

ScoreManager "1" o-- "1" ContadorPuntos
ScoreManager "1" *-- "1..*" Record

DetectorColisiones "1" o-- "1..*" Pieza
DetectorColisiones "1" o-- "1" Tablero
DetectorColisiones "1" o-- "0..*" PowerUp

Aleatorio --|> IA
IA "1" o-- "1" Control

@enduml
